exynos: Revert "ssp: update dependencies"
This reverts commit 74ba595de0feb9270b4213d134f584a44cecda32.

Not relevant for Android 13, only 14+:
error: hardware/samsung_slsi-linaro/exynos/ssp/strongbox_keymint/strongbox_test/functional_vts/Android.bp:17:1: module "strongbox_km_test" variant "android_arm64_armv8-2a": android.hardware.security.keymint-V3-ndk is disallowed in release version because it is unstable, and its "owner" property is missing.

Change-Id: I5798530ff6612d760746fb52c6fd798260cb4e91